name: Docker Image CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend image
        run: |
          docker build ./backend \
            --file ./backend/Dockerfile \
            --tag agrisim-backend

      - name: Build frontend image
        run: |
          docker build ./frontend \
            --file ./frontend/Dockerfile \
            --tag agrisim-frontend